import type { Theme } from '@/type'

export const theme: Theme = {
  colors: {
    primary: '#6366f1',
    primaryForeground: '#ffffff',
    secondary: '#8b5cf6',
    secondaryForeground: '#374151',
    accent: '#e0e7ff',
    accentForeground: '#374151',
    background: '#f8fafc',
    backgroundSecondary: '#1e293b',
    cardBackground: '#ffffff',
    cardForeground: '#1e293b',
    popOverBackground: '#ffffff',
    popOverForeground: '#1e293b',
    muted: '#f3f4f6',
    mutedForeground: '#6b7280',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#d1d5db',
    input: '#d1d5db',
    ring: '#6366f1',
    sidebar: {
      sidebarBackground: '#f3f4f6',
      sidebarForeground: '#1e293b',
      sidebarPrimary: '#6366f1',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#e0e7ff',
      sidebarAccentForeground: '#374151',
      sidebarBorder: '#d1d5db',
      sidebarRing: '#6366f1',
    },
  },
  headerHeight: '64px',
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  typography: {
    fontFamily: {
      body: `'Barlow', 'Noto Sans Thai', 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`,
      heading: `'Barlow', 'Noto Sans Thai', 'Inter', Georgia, serif`,
      mono: 'Monaco, Courier, monospace',
    },
    fontSize: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '18px',
      xl: '20px',
      '2xl': '24px',
      '3xl': '30px',
      '4xl': '36px',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
  },
  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
  },
  breakpoints: {
    mobile: '640px',
    tablet: '768px',
    desktop: '1024px',
    wide: '1280px',
  },
}
